### ISSUE TITLE
Donate button seems to re-render?

### ISSUE THREAD

**Issue by easherma** [state-matters/state-matters-website#103]
@pkrawc @grace000 if you notice, on the site, when it first loads there is some goofy dancing around with the Donate button (IIRC we're applying some custom styling over their embed code).

However, this dance also happens when click the dropdown menu and looks kinda odd. 
I supect it may have to do with when the donate element is being called in the component lifecycle?

**Comment by pkrawc** [comment]
@easherma Ah, you're right I think. IIRC we remove and remount the `Donate` button when the header dropdown is open. We instantiate that third parties class on `componentDidMount` which means we're building a new instance each time the menu is toggled.

Solution could be just to add a class called `hidden` or something to the button instead of removing it. That class would have styling like below.

```css
.hidden {
    display: none;
}
```

This would prevent the button from being un-mounted but allow for the styling of the header to not be screwed up.

**Comment by easherma** [comment]
@pkrawc  isn't that happening here: https://github.com/state-matters/state-matters-website/blob/b5f01929069161577ee0e684b4f8d2de1ea86dad/client/components/Donate.js#L27

**Comment by pkrawc** [comment]
Right. The method componentDidMount is firing more than once in the lifecycle of the app because I believe I wrote the donate button to unmount when the drop-down is open.

**Comment by pkrawc** [comment]
That would be solved by changing stuff in the `Header` component.

**Comment by easherma** [comment]
Hmm, I'm not sure I'm getting this. I tried playing around in both parts of the codebase but don't fully follow whats happening.
